#!/usr/bin/env sh

kernel="$1"
[[ -n "$kernel" ]] || exit 0

# use already installed kernel if it exists
[[ ! -f "$KERNELDESTINATION" ]] || kernel="$KERNELDESTINATION"

toolchain_dir="$( dirname "$( readlink -e "$0" )" )/.."
key="${toolchain_dir}/mok/mok.key"
cert="${toolchain_dir}/mok/mok.crt"

if ! sbverify --cert "$cert" "$kernel" &>/dev/null; then
    sbsign "$kernel" --key "$key" --cert "$cert" --output "$kernel"
fi
